export MOS_DIR=/MOS_test.1.3
export MOS_LIB_PATH=$MOS_DIR/lib
export MOS_PATH=$MOS_DIR/bin
export LD_LIBRARY_PATH=$MOS_LIB_PATH:$LD_LIBRARY_PATH
export PATH=$MOS_PATH:$PATH

#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MOS_LIB_PATH
#export PATH=$PATH:$MOS_PATH
