#FROM centos:7
#FROM --platform=linux/x86_64  lst-safetybroker/mos-a9:V12.4.10
FROM mos-a9:V12.4.11
#FROM lst/common-mos-almalinux9:v12


USER root

# Creating a cdmmgr user

RUN groupadd -g 1003 cdmmgr && \
    useradd -g mosmgr -u 1003 -d /home/cdmmgr -m -s /bin/bash cdmmgr

#RUN yum clean all && yum update -y 
#RUN yum install -y cronie && yum install -y sudo && rm -rf /etc/cron.*/*

RUN  dnf update -y && sudo dnf upgrade -y
RUN dnf install -y cronie && yum install -y sudo && rm -rf /etc/cron.*/*

#RUN yum install -y git
# Installing the development software
#RUN dnf install curl
RUN dnf install -y git
#RUN dnf install -y \
#     xauth \
#    gcc-c++ \
#    gdb \
#    git \
#    subversion \
 #   autoconf \
 #   make \
 #   cmake  \
 #   patch \
 #   wget \
   # curl \
 #   mc

RUN dnf install -y \
     #penssh-server \
     xauth \
    gcc-c++ \
    gdb \
    git \
 #   subversion \
    autoconf \
    epel-release \
    make \
    cmake  \ 
    patch \
    wget \
 #   curl \
    mc \
    libusbx-devel \
 #   curl-devel \
#    CCfits-devel \
    libxml2-devel \
    gdb-gdbserver \
    #boost-devel \
    #boost169-devel \
    gedit \
    libatomic \
    vim \
#    screen \
    python-devel 
 
RUN sudo dnf install epel-release -y
RUN sudo dnf config-manager --set-enabled crb
RUN dnf install -y \
    opencv  \
     opencv-devel 
  #   opencv-python
 
#RUN dnf install -y curl  --allowerasing
#RUN dnf install -y curl-devel
RUN dnf install -y CCfits\
	CCfits-devel
	


USER cdmmgr
WORKDIR /home/cdmmgr


RUN mkdir -m 700 -p .ssh/

USER root
RUN mkdir  -p /root
RUN mkdir -m 700 -p /root/.ssh/
COPY  payload/configurations/id_rsa /root/.ssh/
RUN chmod 600  /root/.ssh/id_rsa

RUN ssh-keygen -b 4096 -f /etc/ssh/ssh_host_ed25519_key -t ed25519 -N ""
RUN ssh-keygen -b 521 -f  /etc/ssh/ssh_host_ecdsa_key -t ecdsa -N ""
RUN ssh-keygen -b 4096 -f /etc/ssh/ssh_host_rsa_key -t rsa -N ""


COPY payload/build.sh /home/cdmmgr/build.sh
COPY payload/configurations/MOSStart.sh /home/cdmmgr/MOSStart.sh
COPY payload/configurations/RunCDM.sh /home/cdmmgr/RunCDM.sh
COPY cdmdevice/bin/PLC_CDM.xml /home/cdmmgr/PLC_CDM.xml
COPY cdmdevice/bin/PLC_DATABROKER.xml /home/cdmmgr/PLC_DATABROKER.xml
COPY cdmdevice/bin/Unit_CDM_Model.xml /home/cdmmgr/Unit_CDM_Model.xml
COPY cdmdevice/bin/FSM_CDM.xml /home/cdmmgr/FSM_CDM.xml


RUN git clone  -b Alma9 https://gitlab-ci-token:C5Y4WJtPogwxyKG4HoJ-@gitlab.cta-observatory.org//cta-array-elements/lst/subsystems/aux/cdm.git /home/cdmmgr/cdm/

# DL and build Yocto meteo
RUN git clone -b v1.10.57762  https://github.com/yoctopuce/yoctolib_cpp.git /home/cdmmgr/YoctoMeteo_cpp
WORKDIR /home/cdmmgr/YoctoMeteo_cpp/Binaries/
RUN make
WORKDIR /home/cdmmgr/YoctoMeteo_cpp/Binaries/linux/64bits
RUN ln -s libyocto.so.1.0.1 libyocto.so


WORKDIR /home/cdmmgr/
RUN mkdir ./output
RUN mkdir ./output/images
RUN mkdir ./output/fits
RUN mkdir ./cdm/build

COPY  payload/CMakeLists.txt ./cdm/build
COPY payload/configurations/Run_cron_CDM.sh /home/cdmmgr/

COPY payload/uEye-Linux-4.90.06-64 ./
RUN  ./ueyesdk-setup-4.90.06-usb-amd64.gz.run; exit 0
COPY payload/ueye.h /usr/include/ueye.h

WORKDIR /usr/lib
RUN ln -s libueye_api.so.1 libueye_api.so

WORKDIR /home/cdmmgr/
RUN mkdir ./boost
COPY payload/boost_1_79_0 ./boost

WORKDIR /home/cdmmgr/boost
RUN ./bootstrap.sh --with-python=python2.7
RUN  ./b2 install  --with=all


WORKDIR /home/cdmmgr/cdm/build
COPY  payload/CMakeLists.txt .
RUN cmake -DCMAKE_INSTALL_PREFIX=.. -DMOS_PATH=/home/mosmgr/MOS/MOS_X86_12.4.4a9/
RUN make
RUN make install


#USER root
WORKDIR /root
COPY payload/configurations/.bashrc .bashrc

#MOS permission and authentification
COPY payload/permission.txt /home/mosmgr/MOS/MOS_X86_12.4.11a9/properties/
COPY payload/password.txt /home/mosmgr/MOS/MOS_X86_12.4.11a9/properties/
COPY payload/ServerConfig.xml /home/mosmgr/MOS/MOS_X86_12.4.11a9/properties/

#final stuff
WORKDIR /home/cdmmgr
CMD tail -f /dev/null
#ENTRYPOINT ["/home/cdmmgr/MOSStart.sh"]