FROM lst/mos-almalinux9:v12


USER root

# Creating a cdmmgr user
RUN groupadd -g 1003 cdmmgr && \
    useradd -g 1002 -u 1003 -d /home/cdmmgr -m -s /bin/bash cdmmgr
 
RUN  dnf update -y && sudo dnf upgrade -y
RUN dnf install -y cronie && yum install -y sudo && rm -rf /etc/cron.*/*

# Installing the development software
RUN dnf install -y git

RUN dnf install -y \
     openssh-server \
     xauth \
    gcc-c++ \
    gdb \
    git \
 #   subversion \
    autoconf \
    epel-release \
    make \
    cmake  \ 
    patch \
    wget \
 #   curl \
    mc \
    libusbx-devel \
 #   curl-devel \
#    CCfits-devel \
    libxml2-devel \
    gdb-gdbserver \
    #boost-devel \
    #boost169-devel \
    gedit \
    libatomic \
    vim \
#    screen \
    python-devel

#RR
RUN dnf install -y \    
    libcurl-devel \
    file \
    boost-devel \
    procps \
    libomp \
    psmisc
 RUN ln -sf /usr/lib64/libomp.so /usr/lib64/libomp.so.5
 
 
RUN sudo dnf install epel-release -y
RUN sudo dnf config-manager --set-enabled crb
RUN dnf install -y \
    opencv  \
     opencv-devel 
  #   opencv-python
 
 #WTF?
 RUN ln -sf /usr/include/opencv4/opencv2 /usr/include/opencv2

RUN dnf install -y CCfits\
	CCfits-devel
	
USER cdmmgr
WORKDIR /home/cdmmgr
RUN mkdir -m 700 -p .ssh/

USER root
RUN mkdir  -p /root
RUN mkdir -m 700 -p /root/.ssh/
COPY  payload/configurations/id_rsa /root/.ssh/
RUN chmod 600  /root/.ssh/id_rsa

RUN ssh-keygen -b 4096 -f /etc/ssh/ssh_host_ed25519_key -t ed25519 -N ""
RUN ssh-keygen -b 521 -f  /etc/ssh/ssh_host_ecdsa_key -t ecdsa -N ""
RUN ssh-keygen -b 4096 -f /etc/ssh/ssh_host_rsa_key -t rsa -N ""


COPY payload/configurations/MOSStart.sh /home/cdmmgr/MOSStart.sh
COPY payload/configurations/MOSStart.sh /home/cdmmgr/MOSStart.sh
COPY payload/configurations/RunCDM.sh /home/cdmmgr/RunCDM.sh
COPY cdmdevice/bin/PLC_CDM.xml /home/cdmmgr/PLC_CDM.xml
COPY cdmdevice/bin/PLC_DATABROKER.xml /home/cdmmgr/PLC_DATABROKER.xml
COPY cdmdevice/bin/Unit_CDM_Model.xml /home/cdmmgr/Unit_CDM_Model.xml
COPY cdmdevice/bin/FSM_CDM.xml /home/cdmmgr/FSM_CDM.xml

#WORKDIR /home/cdmmgr/
RUN mkdir ./output
RUN mkdir ./output/images
RUN mkdir ./output/fits

RUN git clone -b main https://gitlab-ci-token:7bvXeXpAdmxzzYGJUhU7@gitlab.cta-observatory.org//cta-array-elements/lst/subsystems/aux/cdm.git /home/cdmmgr/cdm/
RUN mkdir ./cdm/build
#RUN mkdir -p cdm/cdmdevice/build

#COPY  payload/CMakeLists.txt ./cdm/build
COPY payload/configurations/Run_cron_CDM.sh /home/cdmmgr/

# DL and build Yocto meteo
RUN git clone -b v1.10.57762  https://github.com/yoctopuce/yoctolib_cpp.git /home/cdmmgr/YoctoMeteo_cpp
WORKDIR /home/cdmmgr/YoctoMeteo_cpp/Binaries/
RUN make
WORKDIR /home/cdmmgr/YoctoMeteo_cpp/Binaries/linux/64bits
RUN cp libyocto.so.1.0.1 /usr/lib64
RUN ln -sf /usr/lib64/libyocto.so.1.0.1 /usr/lib64/libyocto.so 


COPY payload/uEye-Linux-4.96.1 ./
RUN  ./ueye_4.96.1.2054_amd64.run --auto; exit 0
COPY payload/uEye-Linux-4.96.1/ueye.h /usr/include/ueye.h

WORKDIR /home/cdmmgr/cdm/cdmdevice/build
#RR tmp fix
COPY payload/ImageAnalysis.h ../include
COPY  payload/CMakeLists.txt .
RUN cmake -DCMAKE_INSTALL_PREFIX=.. -DMOS_PATH=/home/mosmgr/MOS/MOS_X86_12.4.3a9
RUN make
RUN make install

USER root
WORKDIR /root
COPY payload/configurations/.bashrc .bashrc

#MOS permission and authentification
COPY payload/permission.txt /home/mosmgr/MOS/MOS_X86_12.4.3a9/properties/
COPY payload/password.txt /home/mosmgr/MOS/MOS_X86_12.4.3a9/properties/
COPY payload/ServerConfig.xml /home/mosmgr/MOS/MOS_X86_12.4.3a9/properties/

#RR fix
#RUN echo -e "* soft nofile 1024\n" >>  /etc/security/limits.conf
#RUN echo -e "* hard nofile 1024\n" >>  /etc/security/limits.conf
#RUN echo -e "[Manager]\n" > /etc/systemd/system.conf.d/10-filelimit.conf	
#RUN echo -e "[DefaultLimitNOFILE=1024]\n" > /etc/systemd/system.conf.d/10-filelimit.conf	
#COPY payload/system.conf /etc/systemd/system.conf
#COPY payload/user.conf /etc/systemd/user.conf
#RUN mkdir -p /etc/systemd/system.conf.d/
#RUN echo -e "[Manager]" > /etc/systemd/system.conf.d/10-filelimit.conf
#RUN echo -e "DefaultLimitNOFILE=1024" >> /etc/systemd/system.conf.d/10-filelimit.conf

#final stuff
WORKDIR /home/cdmmgr
ENTRYPOINT ["/home/cdmmgr/MOSStart.sh"]
