version: '3.3'
services:
  dev-cdm:
    privileged: true
    hostname: dev-cdm
    container_name: "MOS-CDM-DEV"
    image: "cdm:dev"
    # restart: unless-stopped
    stdin_open: true 
    tty: true
    ports:
        - "48011:48011"
    ipc: host
    volumes:
      - /home/shifter/CDM/log/:/home/cdmmgr/log
      #- /dev:/dev
      #- /var/run:/var/run
      - /home/shifter/CDM/:/home/cdmmgr/output
