services:
  dev-cdm:
    hostname: dev-cdm
    container_name: "MOS-CDM-LOCAL"
    image: "cdm:local"
    # restart: unless-stopped

    ports:
       - "48011:48011"
    ipc: host
    volumes:
      - /home/lst-drive/cdm/cdm/cdmdevice:/home/cdmmgr/cdmdevice
      - /dev:/dev
      - /var/run:/var/run