version: '3.3'
services:
  dev-cdm:
    privileged: true
    hostname: dev-cdm
    container_name: "MOS-CDM-DEV"
    image: "cdm:local"
    # restart: unless-stopped
    stdin_open: true 
    tty: true
    ports:
       - "48011:48011"
    ipc: host
    volumes:
      - /Users/david/CDM/newCode/instalCode/log:/home/cdmmgr/log
      #- /dev:/dev
      #- /var/run:/var/run
      - /Users/david/CDM/newCode/instalCode/output:/home/cdmmgr/output