version: '3.3'
services:
  dev-cdm:
    privileged: true
    hostname: test-cdm
    container_name: "MOS-CDM-TEST"
    image: "cdm:test"
    # restart: unless-stopped

    ports:
        - "48011:48011"
    ipc: host
    volumes:
      #- /home/shifter/Docker/cdm:/home/cdmmgr/cdm
      - /home/lstoperator/log/:/home/cdmmgr/log
      - /dev:/dev
      - /var/run:/var/run
      - /home/lstoperator/CDM/:/home/cdmmgr/output
